### ISSUE TITLE
Рефактор кода

### ISSUE THREAD

**Issue by mikolasan** [mikolasan/pet-project-navigator#11]
Исправить проблемы, отмеченные сервисами codebeat и codeclimate, чтобы повысить рейтинг... и оценить, что нужно изменить в своих привычках программирования.

**Comment by mikolasan** [comment]
Приложение крашится при использовании кнопки назад, высирая следующий лог:

```
E/InputEventSender: Exception dispatching finished signal.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: java.lang.NoSuchMethodError: No virtual method onBackPressedNotHandled()V in class Landroid/support/v4/app/FragmentActivity; or its super classes (declaration of 'android.support.v4.app.FragmentActivity' appears in /data/app/io.github.mikolasan.petprojectnavigator-1/base.apk)
                        at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:179)
                        at android.app.Activity.onKeyUp(Activity.java:2725)
                        at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
                        at android.app.Activity.dispatchKeyEvent(Activity.java:3026)
                        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:533)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:53)
                        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:254)
                        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
                        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
                        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
                        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
                        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
                        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
                        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                        at android.os.MessageQueue.nativePollOnce(Native Method)
                        at android.os.MessageQueue.next(MessageQueue.java:323)
                        at android.os.Looper.loop(Looper.java:136)
                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                        at java.lang.reflect.Method.invoke(Native Method)
                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
D/AndroidRuntime: Shutting down VM


                  --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: io.github.mikolasan.petprojectnavigator, PID: 2950
                  java.lang.NoSuchMethodError: No virtual method onBackPressedNotHandled()V in class Landroid/support/v4/app/FragmentActivity; or its super classes (declaration of 'android.support.v4.app.FragmentActivity' appears in /data/app/io.github.mikolasan.petprojectnavigator-1/base.apk)
                      at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:179)
                      at android.app.Activity.onKeyUp(Activity.java:2725)
                      at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
                      at android.app.Activity.dispatchKeyEvent(Activity.java:3026)
                      at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:533)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:53)
                      at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:254)
                      at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
                      at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                      at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                      at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
                      at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
                      at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
                      at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
                      at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
                      at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
                      at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
                      at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
                      at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
                      at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
                      at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                      at android.os.MessageQueue.next(MessageQueue.java:323)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Application terminated.
```

**Comment by mikolasan** [comment]
Проблема в том, что я не понимаю, что там за метод ему нужен. На StackOverflow ничего конкретного не нашел. 

Есть предположение, что приложение представляет из себя сейчас Франкенштейна собранного из кусков/классов из разных библиотек, которые конфликтуют (наследованием или еще чем).

Отчего я думаю, что нужно заменить AppCompatActivity на FragmentActivity.

**Comment by mikolasan** [comment]
После удаления aFileChooser проблема исчезла. Несовместимость библиотек видимо. Что там за jar вообще в репе?
